// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"GALV_TitleCommands","status":true,"description":"Allows you to customize what commands appear in the title screen menu.","parameters":{"Default Commands":"New Game,new,always|Continue,con,isSave|Options,opt,always|Quit,quit,always","Mod Condition":"","Mod Commands":""}},
{"name":"ui_Energy","status":true,"description":"","parameters":{}},
{"name":"ui_Time","status":true,"description":"","parameters":{}}
];
