// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"YEP_SectionedGauges","status":true,"description":"v1.03 Section up your gauges to make them easier to read.","parameters":{"---Sections---":"","HP Gauge Sections":"10","MP Gauge Sections":"4","TP Gauge Sections":"4","---Status Menu Core---":"","EXP Gauge Sections":"10","Param Gauge Sections":"10"}},
{"name":"title_common_event","status":true,"description":"(Make sure CommonEvent has no trigger, scriptcall: SceneManager.push(Scene_Title) to exit )","parameters":{"commonId":"","titleMenuName":"Help","mapId":"4"}},
{"name":"SRD_SuperToolsEngine","status":true,"description":"The heart of all maker-style plugins; it adds a playtesting editor that can be opened with F12.","parameters":{"Connect Editor":"true","Auto Open Window":"false","Auto Move Window":"true","Menu Editor Exempt List":"[\"Window_BattleLog\",\"Window_MapName\"]"}},
{"name":"SRD_HUDMaker","status":true,"description":"Allows developers to create their own map-based HUD through an in-game GUI window!","parameters":{"Active Updating":"false","Show During Events":"transparent","Map Global Condition":"","Battle Global Condition":"","Disable Delete Key":"true"}}
];
